apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pravasi-user-management
  name: pravasi-user-management
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: pravasi-user-management
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pravasi-user-management
    spec:
      containers:
      - env:
        - name: RDS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: pravasi-user-management
              key: RDS_DB_NAME
        - name: RDS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: pravasi-user-management
              key: RDS_HOSTNAME
        - name: RDS_PASSWORD
          value: pravasi_dev_password
        - name: RDS_PORT
          valueFrom:
            configMapKeyRef:
              name: pravasi-user-management
              key: RDS_PORT
        - name: RDS_USERNAME
          valueFrom:
            configMapKeyRef:
              name: pravasi-user-management
              key: RDS_USERNAME
        image: npawar43/pravasi-user-management:0.0.2-SNAPSHOT #CHANGE
        name: pravasi-user-management
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8100
#        env: //CHANGE
#          - name: CURRENCY_EXCHANGE_URI
#            value: http://currency-exchange
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: pravasi-user-management
  name: pravasi-user-management
  namespace: default
spec:
  ports:
  - # nodePort: 30701 
    port: 8100 
    protocol: TCP
    targetPort: 8100 
  selector:
    app: pravasi-user-management
  sessionAffinity: None 
  type: NodePort